### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by ikema77** [bepitome/basic-auth#54]
**Describe the bug**
Reset password API only requires a username and the new password which is vulnerable to different attacks, such as dictionary attacks, and brute-forcing.

Ex; Anyone who knows the username can easily change the password.

**To Reproduce**
1. Open any API management tool such as Postman.
2. Hit this endpoint `/api/v1/users/reset`
3. Add below body in the request:

```JSON
{
	"username": "xxxxxxx",
	"npassword": "xxxxxxx"
}
```
4. Then, send a request.

**Expected behavior**
The current password linked to the username should be included in the request to verify the requester.

**Actual behavior**
The new password has been updated.

**Screenshots**
 N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: 10
 
**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android
 - Browser: N/A
 - Version (Emulator): 31.2.10-8420304
 - Version (Android) 11.0 (R)
 
**Additional context**
I would like to thank you for this challenge.

**Comment by mutairibassam** [comment]
@ikema77 thanks for reporting the issue. Fixes have been shipped to develop branch for your testing and confirmation prior include it in the upcoming release.

Please run the below command to get the latest changes:
```bash
git clone --single-branch --branch develop https://github.com/bepitome/basic-auth.git
```
