### ISSUE TITLE
Unneeded Token Authentication

### ISSUE THREAD

**Issue by ikema77** [bepitome/basic-auth#55]
**Describe the bug**
Reset password API requires a token. This is an unnecessary requirement because resetting the password happens before logging in.

**To Reproduce**
1. Go to any API management tool.
2. Hit on /api/v1/users/reset.
3. Go to the headers.
4. You need to provide a token to be able to use this API.

**Expected behavior**
It is expected to be able to reset the password without the need to provide a token in the headers.

**Actual behavior**
Resetting the password with a token.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version 10

**Smartphone (please complete the following information):**
 - Device: Pixel 3 Emulator
 - OS: Android
 - Browser N/A
 - Version (Emulator): 31.2.10-8420304
 - Version (Android) 11.0 (R)

**Additional context**
N/A

**Comment by mutairibassam** [comment]
@ikema77 thanks for reporting the issue. Reset API has been exposed to be accessed without token but there is a minor change you should consider in the API route as it's changed to (`/api/v1/auth/reset/`).

Fixes have been shipped to develop branch for your testing and confirmation prior include it in the upcoming release.

Please run the below command to get the latest changes:
```bash
git clone --single-branch --branch develop https://github.com/bepitome/basic-auth.git
```

**Comment by ikema77** [comment]
@mutairibassam I was able to send a 'PUT' request without including a token, which meets the requirement.
I appreciate your prompt reply and fix for the issue.
