### ISSUE TITLE
Status Code Inconsistency

### ISSUE THREAD

**Issue by adnsawas** [bepitome/basic-auth#62]
**Describe the bug**
When logging in with correct user name but wrong password, the response status code is 401 which is correct
However, when logging in with non-existing username, the response status code is 200. This is make it a bit complex to handle error in front-end.

**To Reproduce**
1. Login with non-existing username. 

**Expected behavior**
The response status code should 4xx instead of 200.

**Comment by mutairibassam** [comment]
@adnsawas response codes have been updated for all the apis and latest changes has been shipped to branch [hotfix/response-codes](https://github.com/bepitome/basic-auth/tree/hotfix/response-codes)

Please pull the latest changes and confirm if there is nothing need to be modified prior deployment.

You can fetch the latest changes using the below commands:
```bash
# should be in a separate directory to avoid conflict with your local git repo.
git clone --single-branch --branch hotfix/response-codes https://github.com/bepitome/basic-auth.git
```
